name: C

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Verify formatting
        run: |
          passed=true
          for file in src/*.[ch] ; do clang-format $file > $file.formatted ; echo $file ; diff $file $file.formatted ; if [ $? != 0 ]; then passed=false ; fi ; rm $file.formatted ; done
          if [ $passed = false ]; then exit 1; fi

      - name: Install dependencies
        run: sudo apt-get install meson ninja-build

      - name: Meson
        run: meson _build

      - name: Test
        run: ninja -C _build test
